config/routes.rb
Rails.application.routes.draw do

  root to: 'website#index'
  get 'show/:id/:from/:to', to: 'website#show'
  get 'new_reservation/:id/:room_id/:from/:to', to: 'website#new_reservation'
  get 'signin', to: 'website#signin'
  post 'signin', to: 'website#signin'
  get 'logout', to: 'website#logout'
  get 'admin', to: 'website#admin', as: 'admin'
  get 'admin/hotel/', to: 'website#hotel_admin', as: 'hotel_admin'
  resources :reservations
  resources :rooms
  resources :users
  resources :hotels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :hotel
    has_many :reservation
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authorization
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @hotels = Hotel.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @hotels = Hotel.all
  end

  # GET /rooms/new
  def new
    @room = Room.new
    @hotels = Hotel.all
  end

  # GET /rooms/1/edit
  def edit
    @hotels = Hotel.all
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:hotel_id, :size, :price)
    end

    def authorization
      if session[:permissions] != 0
        redirect_to signin_url
      end
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hotel_id %>
    <%= form.collection_select :hotel_id, @hotels, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size, id: :room_size, :required => true %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :room_price, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="header-text">
<h1>Editing Room</h1>
</div>
<div class="panel">
<%= render 'form', room: @room %>

<%= link_to 'Show', @room %>
<%= link_to 'Back', rooms_path %>

</div>

app/views/rooms/index.html.erb
<div class="header-text">
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>
</div>
<div class="table-info">
<table class="table-show">
  <thead>
    <tr>
      <th>Hotel</th>
      <th>Size</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= @hotels.find(room.hotel_id).name %></td>
        <td><%= room.size %></td>
        <td><%= room.price %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="link-button">
<%= link_to 'New Room', new_room_path %>
</div>
</div>

app/views/rooms/new.html.erb
<div class="header-text">
<h1>New Room</h1>
</div>
<div class="panel">
<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/show.html.erb
<div class="header-text">
<p id="notice"><%= notice %></p>
</div>
<div class="panel">
<div class="panel-body">
<p>
  <strong>Hotel:</strong>
  <%= @hotels.find(@room.hotel_id).name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>
<div class="link-button">
<%= link_to 'Edit', edit_room_path(@room) %>
<%= link_to 'Back', rooms_path %>
</div>
</div>
</div>