config/routes.rb
Rails.application.routes.draw do

  root to: 'website#index'
  get 'show/:id/:from/:to', to: 'website#show'
  get 'new_reservation/:id/:room_id/:from/:to', to: 'website#new_reservation'
  get 'signin', to: 'website#signin'
  post 'signin', to: 'website#signin'
  get 'logout', to: 'website#logout'
  get 'admin', to: 'website#admin', as: 'admin'
  get 'admin/hotel/', to: 'website#hotel_admin', as: 'hotel_admin'
  resources :reservations
  resources :rooms
  resources :users
  resources :hotels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
    @hotels = Hotel.where(city: params[:city])
    @rooms = Room.all
    @reservations = Reservation.all
    @from = params[:from]
    @to = params[:to]
    @today = Date.today
    @tomorrow = Date.tomorrow
  end

  def show
    @id = params[:id]
    @from = Date.parse(params[:from])
    @to = Date.parse(params[:to])
    @hotel = Hotel.find(@id)
    @rooms = Room.where(hotel_id: @id)

    / @roomTmp =  Room.where(hotel_id: @id).joins(:reservation).where(["date(reservations.from) > ?", @from]) /
  
  end

  def new_reservation 
    @id = params[:id]
    @room = params[:room_id]
    @from = params[:from]
    @to = params[:to]
    @reservation = Reservation.create(user_id: 1, hotel_id: @id, room_id: @room, from: @from, to: @to)

  end

  def signin
    if request.post?
      @login = params[:login]
      @password = params[:password]
      user = User.where(login: @login, password:@password).first
      if user
        session[:hotel_id] =  user.hotel_id
        session[:permissions] =  user.permissions
        if user.permissions > 0
          redirect_to hotel_admin_url
        else
          redirect_to admin_url
        end
      else
        @info = "No user with this data. Try again!"
      end
    end
  end

  def logout
    session[:hotel_id] =  nil
    session[:permissions] = nil
    redirect_to signin_url
  end

  def admin
    if session[:permissions] != 0
      redirect_to signin_url
    end
  end

  def hotel_admin
    if session[:permissions] == 0
      redirect_to signin_url
    end
    @reservations = Reservation.where(hotel_id: session[:hotel_id])
    @rooms = Room.all
  end

end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/website/admin.html.erb
<div class="panel">
<h1>Admin</h1>

<div class="panel-body">
<h3>Edit:</h3>

<ul>
    <li><%= link_to 'Hotels', hotels_path %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Reservations', reservations_path %></li>
    <li><%= link_to 'Rooms', rooms_path %></li>
</ul>
<div class="link-button">
<%= link_to 'Logout', logout_path %>
</div>
</div>
</div>

app/views/website/hotel_admin.html.erb
<div class="header-text">
<h1>Hotel admin</h1>
</div>
<div class="table-info">
<table class="table-show">
        <thead>
            <th>ID</th>
            <th>Room</th>
            <th>From</th>
            <th>To</th>
        </thead>
        <tbody>
            <% @reservations.each do |r| %>
            <tr>
                <td><%= r.id %></td>
                <td><% if r.room_id %><%= @rooms.find(r.room_id).size %><% end %></td>
                <td><%= r.from %></td>
                <td><%= r.to %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <div class="link-button">
<%= link_to 'Logout', logout_path %>
</div>
</div>

app/views/website/index.html.erb
<div class="background-image">
<h1> Find Hotels & Unique Places to Stay </h1>
</div>
<div class="panel">
<%= form_tag "/", :method => 'get'  do %>
    <label for="city"> Destination, property name(city):*: 
        <%= text_field_tag :city, params[:city], :required => true  %>
     </label>
    <label for="from"> Check-in: 
        <%= date_field_tag :from, params[:from], :required => true, :min => @today  %>
    </label>
    <label for="to"> Check-out: 
        <%= date_field_tag :to, params[:to], :required => true, :min => @tomorrow %>
    </label>
  <%= submit_tag 'Search' %>
<% end %>
</div>

<% if @hotels.count > 0 %>
<div class="search-result">
<h3>Yes! we have something!</h3>
    <table>
        <thead>
            <th>#</th>
            <th>Name</th>
            <th>City</th>
            <th>Postcode</th>
            <th>Address</th>
            <th>Rooms</th>
            <th>Action</th>
        </thead>
        <tbody>
            <% @hotels.each do |hotel| %>

            <tr>
                <td><%= hotel.id %></td>
                <td><%= hotel.name %></td>
                <td><%= hotel.city %></td>
                <td><%= hotel.postcode %></td>
                <td><%= hotel.address %></td>
                <td><%= hotel.room.count %></td>
                <td> <a href="/show/<%= hotel.id %>/<%= @from %>/<%= @to %>">Show rooms</a> </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<% end %>

app/views/website/new_reservation.html.erb
  <div class="panel">
  <h1>Congratulations!</h1>
  <h2>Your room is reservated, we wait for You.</h2>
  <table class="table-show">
        <thead>
            <th>Reservation ID</th>
            <th>Check in</th>
            <th>Check out</th>
        </thead>
        <tbody>
        <tr>
  <td><%= @reservation.id %></td>
   <td><%= @from %></td>
    <td><%= @to %></td>
    </tr>
    </tbody>
    </table>
    </div>

app/views/website/show.html.erb
<div class="panel">
<h1>Now available in <%= @hotel.name %> </h1>

<h2>Choose the room!</h2>
    <table class="table-show">
        <thead>
            <th>ID</th>
            <th>Size</th>
            <th>Price</th>
            <th>Status</th>
            <th>Action</th>
        </thead>
        <tbody>
            <% @rooms.each do |room| %>
                <% @status = 'available' %>
                <% room.reservation.each do |date| %>
                    <% if date.from >= @from && date.to <= @to %>
                        <% @status = 'unavailable' %>
                    <% end %>
                <% end %>

                <tr>
                    <td><%= room.id %></td>
                    <td><%= room.size %></td>
                    <td><%= number_with_precision room.price, :precision => 0 %>  zł</td>
                    <td><span class="<%= @status %>"><%= @status %></span></td>
                    <td> 
                        <% if @status == 'available' %>
                            <a href="/new_reservation/<%= @hotel.id %>/<%= room.id %>/<%= @from %>/<%= @to %>">Book now</a> </td>
                        <% end %>
                    <tr>
                </tr>
            <% end %>
        </tbody>

    </table>
</div>

app/views/website/signin.html.erb
<div class="panel">
<h1>Logowanie</h1>

<p><%= @info %></p>

<%= form_tag do %>
    <div class="field">
        <%= label_tag(:login, "Login") %>
        <%= text_field_tag(:login) %>
    </div>

    <div class="field">
        <%= label_tag(:password, "Password") %>
        <%= password_field_tag(:password) %>
    </div>

    <%= submit_tag("Sign in") %>
<% end %>
</div>