config/routes.rb
Rails.application.routes.draw do

  root to: 'website#index'
  get 'show/:id/:from/:to', to: 'website#show'
  get 'new_reservation/:id/:room_id/:from/:to', to: 'website#new_reservation'
  get 'signin', to: 'website#signin'
  post 'signin', to: 'website#signin'
  get 'logout', to: 'website#logout'
  get 'admin', to: 'website#admin', as: 'admin'
  get 'admin/hotel/', to: 'website#hotel_admin', as: 'hotel_admin'
  resources :reservations
  resources :rooms
  resources :users
  resources :hotels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many :room
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authorization
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :address, :postcode, :city)
    end

    def authorization
      if session[:permissions] != 0
        redirect_to signin_url
      end
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel, local: true) do |form| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :hotel_name, :required => true%>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :hotel_address, :required => true %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_field :postcode, id: :hotel_postcode, :required => true %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :hotel_city, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<div class="header-text">
<h1>Editing Hotel</h1>
</div>
<div class="panel">
<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>
</div>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>
<div class="header-text">
<h1>Hotels</h1>
</div>
<div class="table-info">
<table class="table-show" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Postcode</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.address %></td>
        <td><%= hotel.postcode %></td>
        <td><%= hotel.city %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="link-button">
<%= link_to 'New Hotel', new_hotel_path %>
</div>
</div>

app/views/hotels/new.html.erb
<div class="header-text">
<h1>New Hotel</h1>
</div>
<div class="panel">
<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>
</div>

app/views/hotels/show.html.erb
<div class="panel">
<div class="panel-body">
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @hotel.postcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @hotel.city %>
</p>
<div class="link-button">
<%= link_to 'Edit', edit_hotel_path(@hotel) %> 
<%= link_to 'Back', hotels_path %>
</div>
</div>
</div>